package com.sv.model;
// Generated 11-13-2016 06:54:17 PM by Hibernate Tools 4.3.1



/**
 * Actividades generated by hbm2java
 */
public class Actividades  implements java.io.Serializable {


     private Integer id;
     private Proyecto proyecto;
     private Recurso recurso;
     private String nombreActividad;
     private String fechaRealizacion;
     private Integer cantidad;
     private Float total;

    public Actividades() {
    }

	
    public Actividades(Proyecto proyecto, Recurso recurso) {
        this.proyecto = proyecto;
        this.recurso = recurso;
    }
    public Actividades(Proyecto proyecto, Recurso recurso, String nombreActividad, String fechaRealizacion, Integer cantidad, Float total) {
       this.proyecto = proyecto;
       this.recurso = recurso;
       this.nombreActividad = nombreActividad;
       this.fechaRealizacion = fechaRealizacion;
       this.cantidad = cantidad;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public Recurso getRecurso() {
        return this.recurso;
    }
    
    public void setRecurso(Recurso recurso) {
        this.recurso = recurso;
    }
    public String getNombreActividad() {
        return this.nombreActividad;
    }
    
    public void setNombreActividad(String nombreActividad) {
        this.nombreActividad = nombreActividad;
    }
    public String getFechaRealizacion() {
        return this.fechaRealizacion;
    }
    
    public void setFechaRealizacion(String fechaRealizacion) {
        this.fechaRealizacion = fechaRealizacion;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }




}


