package com.sv.model;
// Generated 11-13-2016 06:54:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DetalleInforme generated by hbm2java
 */
public class DetalleInforme  implements java.io.Serializable {


     private int id;
     private String detalleInformecol;
     private Set informeses = new HashSet(0);

    public DetalleInforme() {
    }

	
    public DetalleInforme(int id) {
        this.id = id;
    }
    public DetalleInforme(int id, String detalleInformecol, Set informeses) {
       this.id = id;
       this.detalleInformecol = detalleInformecol;
       this.informeses = informeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDetalleInformecol() {
        return this.detalleInformecol;
    }
    
    public void setDetalleInformecol(String detalleInformecol) {
        this.detalleInformecol = detalleInformecol;
    }
    public Set getInformeses() {
        return this.informeses;
    }
    
    public void setInformeses(Set informeses) {
        this.informeses = informeses;
    }




}


