package com.sv.model;
// Generated 11-13-2016 06:54:17 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Informes generated by hbm2java
 */
public class Informes  implements java.io.Serializable {


     private Integer id;
     private DetalleInforme detalleInforme;
     private Proyecto proyecto;
     private String descripcion;
     private Date fecha;
     private String fechaFin;

    public Informes() {
    }

	
    public Informes(DetalleInforme detalleInforme, Proyecto proyecto) {
        this.detalleInforme = detalleInforme;
        this.proyecto = proyecto;
    }
    public Informes(DetalleInforme detalleInforme, Proyecto proyecto, String descripcion, Date fecha, String fechaFin) {
       this.detalleInforme = detalleInforme;
       this.proyecto = proyecto;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.fechaFin = fechaFin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DetalleInforme getDetalleInforme() {
        return this.detalleInforme;
    }
    
    public void setDetalleInforme(DetalleInforme detalleInforme) {
        this.detalleInforme = detalleInforme;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }




}


