package com.sv.model;
// Generated 11-13-2016 06:54:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Recurso generated by hbm2java
 */
public class Recurso  implements java.io.Serializable {


     private int idRecurso;
     private String tipo;
     private Float precio;
     private Set actividadeses = new HashSet(0);

    public Recurso() {
    }

	
    public Recurso(int idRecurso) {
        this.idRecurso = idRecurso;
    }
    public Recurso(int idRecurso, String tipo, Float precio, Set actividadeses) {
       this.idRecurso = idRecurso;
       this.tipo = tipo;
       this.precio = precio;
       this.actividadeses = actividadeses;
    }
   
    public int getIdRecurso() {
        return this.idRecurso;
    }
    
    public void setIdRecurso(int idRecurso) {
        this.idRecurso = idRecurso;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Set getActividadeses() {
        return this.actividadeses;
    }
    
    public void setActividadeses(Set actividadeses) {
        this.actividadeses = actividadeses;
    }




}


