package com.sv.model;
// Generated 11-13-2016 06:54:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String rolcol;
     private Set usuarioses = new HashSet(0);

    public Rol() {
    }

    public Rol(String rolcol, Set usuarioses) {
       this.rolcol = rolcol;
       this.usuarioses = usuarioses;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getRolcol() {
        return this.rolcol;
    }
    
    public void setRolcol(String rolcol) {
        this.rolcol = rolcol;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


