package com.sv.model;
// Generated 11-13-2016 06:54:17 PM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idUsuarios;
     private Rol rol;
     private String nombre;
     private String departamento;
     private String password;

    public Usuarios() {
    }

	
    public Usuarios(int idUsuarios, Rol rol) {
        this.idUsuarios = idUsuarios;
        this.rol = rol;
    }
    public Usuarios(int idUsuarios, Rol rol, String nombre, String departamento, String password) {
       this.idUsuarios = idUsuarios;
       this.rol = rol;
       this.nombre = nombre;
       this.departamento = departamento;
       this.password = password;
    }
   
    public int getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


